/* ═══ NEITO_EMOTIONS — BỘ TRẠNG THÁI BIỂU CẢM NHÂN VẬT (nguồn duy nhất) ═══
 * Dùng chung: main.js (require), overlay.html + dashboard.html (<script src>).
 * id      = key máy trạng thái = tên file pose của nhân vật ảnh (idle.png…)
 * anim    = animation CSS gắn theo [data-emo]
 * eyes/mouth/extras = class nhóm SVG bật lên cho state này (default slime)
 * pose    = có ô upload riêng trong modal Tạo nhân vật (ảnh/GIF/WebP)
 * gen     = mô tả ANH chuẩn hóa để model AI sinh đúng tư thế
 * trigger = khi nào app tự bật (ghi chú cho người + guide)
 */
(function (root, factory) {
  const LIST = factory();
  if (typeof module === 'object' && module.exports) module.exports = { NEITO_EMOTIONS: LIST };
  else root.NEITO_EMOTIONS = LIST;
})(typeof self !== 'undefined' ? self : this, function () {
  return [
    { id: 'idle',      vi: 'Đứng yên',   icon: '🧍', anim: 'breathe', eyes: ['eyes-open'], mouth: ['m-omega'], extras: [], pose: true,
      alias: ['dung_yen','stand'],
      gen: 'calm neutral face, gentle omega mouth, standing still on the ground',
      trigger: 'mặc định khi không có sự kiện' },
    { id: 'march',     vi: 'Di chuyển tại chỗ', icon: '🚶', anim: 'march', eyes: ['eyes-open'], mouth: ['m-flat'], extras: [], pose: true,
      alias: ['di_chuyen','move','walking','đi'],
      gen: 'walking in place pose, slight body lean, flat focused mouth',
      trigger: 'mắt thấy Sếp di chuyển nhân vật trong game / kéo cửa sổ' },
    { id: 'bounce',    vi: 'Nhún nhảy', icon: '🎵', anim: 'boing', eyes: ['eyes-open'], mouth: ['m-smile'], extras: ['notes'], pose: true,
      alias: ['nhun_nhay','hop','boing'],
      gen: 'happy bouncing pose, smiling, music notes around',
      trigger: 'click vào nhân vật, nhịp vui nhẹ' },
    { id: 'happy',     vi: 'Vui', icon: '😊', anim: 'hop', eyes: ['eyes-happy'], mouth: ['m-smile'], extras: ['sparkles','blush-strong'], pose: true,
      alias: ['vui','vang','sun','nho'],
      gen: 'big happy smile, closed arched eyes, sparkles',
      trigger: 'khen, tin tốt, win, hoàn thành việc' },
    { id: 'laugh',     vi: 'Cười phá', icon: '😆', anim: 'rock', eyes: ['eyes-laugh'], mouth: ['m-laugh'], extras: ['notes'], pose: true,
      alias: ['cuoi','cười'],
      gen: 'laughing hard, squinted eyes, wide open mouth',
      trigger: 'Sếp đùa / câu hài' },
    { id: 'sad',       vi: 'Buồn', icon: '😔', anim: 'droop', eyes: ['eyes-sad'], mouth: ['m-frown'], extras: ['brow-sad', 'sigh'], pose: true,
      alias: ['buon','triu','bad'],
      gen: 'sad drooping eyes, tilted brows, frown',
      trigger: 'tin xấu, lỗi, Sếp than phiền' },
    { id: 'curious',   vi: 'Tò mò', icon: '🔍', anim: 'lean', eyes: ['eyes-open'], mouth: ['m-o'], extras: ['qmark'], pose: true,
      alias: ['tomyo','to_mo','qua','interest'],
      gen: 'leaning forward, wide curious eyes, small o mouth, question mark',
      trigger: 'mắt thấy cửa sổ/app lạ, nội dung mới' },
    { id: 'surprise',  vi: 'Bất ngờ', icon: '😮', anim: 'pop', eyes: ['eyes-wide'], mouth: ['m-big'], extras: ['exmark'], pose: true,
      alias: ['batngo','o','surprised'],
      gen: 'surprised wide eyes, big open mouth, exclamation mark',
      trigger: 'sự kiện bất ngờ trên màn hình, tin sốc' },
    { id: 'shock',     vi: 'Hoảng sợ', icon: '😱', anim: 'shiver', eyes: ['eyes-alert'], mouth: ['m-wave'], extras: ['sweat'], pose: true,
      alias: ['hoangso','panic','sot','scream'],
      gen: 'panicked spiral-wide eyes, wavy screaming mouth, sweat drop, trembling',
      trigger: 'combat danger, báo lỗi nặng, nhắc gấp' },
    { id: 'look',      vi: 'Liếc mắt theo con trỏ', icon: '👀', anim: 'tilt', eyes: ['eyes-open'], mouth: ['m-flat'], extras: [], pose: true,
      alias: ['liếc','follow','cursor'],
      gen: 'head slightly tilted, pupils tracking sideways',
      trigger: 'con trỏ chuột di chuyển gần/qua nhân vật' },
    { id: 'ok',        vi: 'OK', icon: '👌', anim: 'nodding', eyes: ['eyes-wink'], mouth: ['m-grin'], extras: [], pose: true,
      alias: ['san_sang','confirm','roger','xong'],
      gen: 'confident wink, smirk, nodding',
      trigger: 'xác nhận lệnh, việc xong' },
    { id: 'yes',       vi: 'Gật đầu', icon: '↕️', anim: 'nodding', eyes: ['eyes-open'], mouth: ['m-smile'], extras: [], pose: true,
      alias: ['gật','nod','dong_y'],
      gen: 'nodding yes, friendly smile',
      trigger: 'đồng ý, xác nhận' },
    { id: 'no',        vi: 'Lắc đầu', icon: '↔️', anim: 'shaking', eyes: ['eyes-uneven'], mouth: ['m-frown'], extras: ['sweat'], pose: true,
      alias: ['lắc','shake','khong','từ_chối'],
      gen: 'shaking head no, worried uneven eyes',
      trigger: 'từ chối, cảnh báo không nên' },
    { id: 'think',     vi: 'Suy nghĩ', icon: '🤔', anim: 'sway', eyes: ['eyes-up'], mouth: ['m-flat'], extras: ['bub'], pose: true,
      alias: ['nghi','ngẫm','nghi_ngờ','processing'],
      gen: 'thinking, eyes looking up, flat mouth, thought bubble',
      trigger: 'đang tra cứu / ngẫm' },
    { id: 'doubt',     vi: 'Thắc mắc', icon: '❓', anim: 'lean', eyes: ['eyes-half'], mouth: ['m-smirk'], extras: ['qmark'], pose: true,
      alias: ['thacmac','hmm','nghi_ngo'],
      gen: 'doubtful raised eyebrow, small question mark',
      trigger: 'thông tin mâu thuẫn, Sếp hỏi lạ' },
    { id: 'sleep',     vi: 'Ngủ gật', icon: '😴', anim: 'doze', eyes: ['eyes-closed'], mouth: ['m-flat'], extras: ['zzz'], pose: true,
      alias: ['ngu','dream','nga'],
      gen: 'sleeping closed eyes, zzz floating',
      trigger: '10 phút không tương tác' },
    {
    id: 'listening', vi: 'Đang nghe', icon: '🎙',
    anim: 'breathe', eyes: ['eyes-up'], mouth: ['m-smile'],
    extras: ['extras-listening'], pose: false,
    gen: 'attentive listening, eyes looking up toward speaker, sound rings around head',
    trigger: 'mic bật — Neito Agent đang chờ nghe Sếp nói',
  },
  {
    id: 'heard', vi: 'Nghe rồi!', icon: '💡',
    anim: 'pop', eyes: ['eyes-wide'], mouth: ['m-o'],
    extras: ['exmark'], pose: false,
    gen: 'aha moment, eyes wide, small O mouth, exclamation flash',
    trigger: 'mic vừa bắt xong một câu trọn vẹn',
  },
  
  { id: 'talk',      vi: 'Nói', icon: '💬', anim: 'breathe', eyes: ['eyes-open'], mouth: ['m-o'], extras: [], pose: true,
      alias: ['speaking','dang_noi'],
      gen: 'talking open round mouth mid-speech, lively eyes',
      trigger: 'TTS đang phát (miệnh nhép theo tiếng thật)' },
    { id: 'cry',       vi: 'Khóc', icon: '😢', anim: 'droop', eyes: ['eyes-cry'], mouth: ['m-cry'], extras: ['tears'], pose: true,
      alias: ['khoc','kick','dau','đau','buon_dau'],
      gen: 'crying with tear drops streaming, sad open mouth',
      trigger: 'thất bại nặng, lose, Sếp buồn lắm' },
    { id: 'angry',     vi: 'Giận', icon: '😤', anim: 'shiver', eyes: ['eyes-angry'], mouth: ['m-flat'], extras: ['steam'], pose: true,
      alias: ['gian','dỗi','grr'],
      gen: 'angry furrowed brows, steam puffs',
      trigger: 'lỗi lặp, bị bắt lỗi' },
    { id: 'love',      vi: 'Yêu', icon: '💖', anim: 'hop', eyes: ['eyes-love'], mouth: ['m-smile'], extras: ['hearts','blush-strong'], pose: true,
      alias: ['thuong','happy_heart'],
      gen: 'heart eyes, sweet smile, floating hearts',
      trigger: 'Sếp khen / dễ thương' },
    { id: 'cool',      vi: 'Chất', icon: '😎', anim: 'sway', eyes: ['eyes-cool'], mouth: ['m-smirk'], extras: [], pose: true,
      alias: ['ngau','pro','swagger'],
      gen: 'sunglasses cool smirk',
      trigger: 'Sếp làm gì đó chất, thắng đẹp' },
    {
    id: 'stretch', vi: 'Ưỡn người', icon: '🧘',
    anim: 'stretch', eyes: ['eyes-closed'], mouth: ['m-o'],
    extras: [], pose: false,
    gen: 'stretching body tall then squash back, eyes shut, small yawn O',
    trigger: 'NPC idle — vươn vai sinh vật',
  },
  { id: 'blink_cute',vi: 'Nháy mắt', icon: '😉', anim: 'pop', eyes: ['eyes-wink'], mouth: ['m-smile'], extras: ['sparkles', 'blush'], pose: true,
      alias: ['wink','nháy','quẩy'],
      gen: 'one eye wink, grin, sparkle',
      trigger: 'chào / trêu' },
    { id: 'star',      vi: 'Mắt lấp lánh', icon: '🤩', anim: 'lean', eyes: ['eyes-sparkle'], mouth: ['m-big'], extras: ['sparkles'], pose: true,
      alias: ['sao','wow','kinh_thán'],
      gen: 'starry sparkling eyes, awe open mouth',
      trigger: 'phát hiện thứ hay ho, Sếp khoe chiến tích' },
    { id: 'tremble',   vi: 'Run rẩy', icon: '🥶', anim: 'tremble', eyes: ['eyes-spiral'], mouth: ['m-wave'], extras: ['sweat'], pose: true,
      alias: ['lẩy_bẩy','run','sợ_vừa'],
      gen: 'trembling slightly, nervous uneven eyes',
      trigger: 'nhắc chuyện tế nhị / Sếp gắt vừa' },
    { id: 'transform', vi: 'Biến đổi', icon: '✨', anim: 'spinT', eyes: ['eyes-open'], mouth: ['m-omega'], extras: ['flash', 'core'], pose: true,
      alias: ['doi_nhan_vat','morph'],
      gen: '(hiệu ứng chuyển hình — app tự xoay + lóe sáng, không cần ảnh)',
      trigger: 'kích hoạt MỖI LẦN Sếp đổi nhân vật' }
  ];
});
